// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OFIN.Models;

namespace OFIN.Migrations.UserLog
{
    [DbContext(typeof(UserLogContext))]
    [Migration("20200602043637_MigrateLog")]
    partial class MigrateLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OFIN.Models.UserLog", b =>
                {
                    b.Property<string>("fLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fAction");

                    b.Property<string>("fActionDesc");

                    b.Property<DateTime>("fDate");

                    b.Property<string>("fUsername");

                    b.HasKey("fLogId");

                    b.ToTable("tUserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
