// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OFIN.Models.Merchant;

namespace OFIN.Migrations.Item
{
    [DbContext(typeof(ItemContext))]
    [Migration("20200602052446_MigrationItem")]
    partial class MigrationItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OFIN.Models.Merchant.Item", b =>
                {
                    b.Property<string>("fItemCode");

                    b.Property<int>("fItemBought");

                    b.Property<string>("fItemDesc");

                    b.Property<string>("fItemPrice");

                    b.HasKey("fItemCode");

                    b.ToTable("tMerchant");
                });
#pragma warning restore 612, 618
        }
    }
}
