// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OFIN.Models.Payment;

namespace OFIN.Migrations.Payment
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20200602062505_PaymentCon")]
    partial class PaymentCon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OFIN.Models.Payment.Payment", b =>
                {
                    b.Property<string>("fPaymentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fItemCode");

                    b.Property<DateTime>("fPaymentDate");

                    b.Property<int>("fQty");

                    b.Property<string>("fUsername");

                    b.HasKey("fPaymentId");

                    b.ToTable("tPayment");
                });
#pragma warning restore 612, 618
        }
    }
}
