// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OFIN.Models;

namespace OFIN.Migrations.Log
{
    [DbContext(typeof(LogContext))]
    [Migration("20200602032218_logContext")]
    partial class logContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OFIN.Models.Logs", b =>
                {
                    b.Property<string>("LogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ErrorCode");

                    b.Property<string>("LogGroup");

                    b.Property<string>("LogMsg");

                    b.HasKey("LogId");

                    b.ToTable("tLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
