// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OFIN.Models.Account;

namespace OFIN.Migrations.AdminDetail
{
    [DbContext(typeof(AdminDetailContext))]
    partial class AdminDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OFIN.Models.Account.AdminDetail", b =>
                {
                    b.Property<string>("fUsername")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fFirstName");

                    b.Property<string>("fGender");

                    b.Property<string>("fIcNumber");

                    b.Property<string>("fLastName");

                    b.HasKey("fUsername");

                    b.ToTable("tAdminDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
